# Generated by Django 3.2.13 on 2022-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=16)),
                ('dataNasc', models.DateField(null=True)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
    ]

