# Generated by Django 3.2.13 on 2022-05-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('codigo_disciplina', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('data_tarefa', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.disciplina')),
            ],
        ),
    ]
