# Generated by Django 3.2.13 on 2022-05-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina'),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
