# Generated by Django 3.2.13 on 2022-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_curso', models.CharField(max_length=50)),
                ('instituicao', models.CharField(max_length=50)),
            ],
        ),
    ]

