# Generated by Django 3.2.13 on 2022-05-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembrete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
