# Generated by Django 3.2.13 on 2022-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembrete', '0002_auto_20220528_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='imagem',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
