# Generated by Django 3.2.13 on 2022-06-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarefa', '0002_auto_20220528_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanDoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.tarefa')),
            ],
        ),
    ]
