# Generated by Django 3.2.13 on 2022-05-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('codigo_disciplina', models.CharField(max_length=7)),
            ],
        ),
    ]
